components_manager:
    coro_pool:
        initial_size: 5000
        max_size: 1000000

    task_processors:

        main-task-processor:
            worker_threads: 4
            thread_name: "main-worker"

        fs-task-processor:
            worker_threads: 10
            thread_name: "fs-worker"

    default_task_processor: main-task-processor

    components:

        server:
            listener:
                port: 8080
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: error
                    overflow_behavior: discard


        tracer:
            service-name: CRUD-datamart


        dynamic-config:
            fs-cache-path: ''
        dynamic-config-fallbacks:
            fallback-path: dynamic_config.json

        testsuite-support: {}

        dns-client:
            fs-task-processor: fs-task-processor

        dbb:
            dbconnection: 'postgresql://ortur:beoboba@localhost:5432/dbb'
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true

        handle-create:
            path: /create/{name}
            method: POST
            task_processor: fs-task-processor

        handle-read:
            path: /read/{id}
            method: GET
            task_processor: main-task-processor

        handle-update:
            path: /update/{id}/{new_name}
            method: PUT
            task_processor: main-task-processor

        handle-delete:
            path: /delete/{id}
            method: DELETE
            task_processor: main-task-processor